### ISSUE TITLE
[Bug] tesseract failed sometimes

### ISSUE THREAD

**Issue by williamfzc** [williamfzc/stagesep2#2]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/stagesep2/analyser/ocr.py", line 38, in exec_tesseract
    tesseract_process.communicate(timeout=5)
  File "/usr/local/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/lib/python3.7/subprocess.py", line 1682, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/local/lib/python3.7/subprocess.py", line 982, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['tesseract', '/tmp/tmpegt7hkcz.png', '/usr/local/lib/python3.7/site-packages/842f1e2a-44e3-11e9-b957-0242ac110002', '-l', 'chi_sim']' timed out after 5 seconds
```

**Comment by williamfzc** [comment]
Caused by file exchange.
https://github.com/williamfzc/stagesep2/pull/4 fixed.
