### ISSUE TITLE
运行DEMO的时候报错

### ISSUE THREAD

**Issue by 1281758787** [williamfzc/stagesep2#6]
C:\Users\lenovo\Downloads\stagesep2\stagesep2-sample-master>python sample.py
2019-06-12 18:19.47 VideoManager                   msg=LOAD VIDEO name=demo path=./videos/demo.mp4
2019-06-12 18:19.48 TemplateManager                msg=LOAD PICTURE name=amazon path=./pictures/amazon.jpg video=demo
2019-06-12 18:19.48 TemplateManager                msg=LOAD PICTURE name=chrome path=./pictures/chrome.jpg video=demo
2019-06-12 18:19.48 TemplateManager                msg=LOAD PICTURE name=chrome_clicked path=./pictures/chrome_clicked.jpg video=demo
2019-06-12 18:19.48 AnalyserRunner                 analyser=[<class 'stagesep2.analyser.ocr.OCRAnalyser'>, <class 'stagesep2.analyser.match_template.MatchTemplateAnalyser'>, <class 'sta
gesep2.analyser.trend.TrendAnalyser'>] video={'demo': <stagesep2.loader.SSVideo object at 0x00000000028652B0>}
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 1.045 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "sample.py", line 28, in <module>
    result1 = AnalysisRunner.run()
  File "C:\Program Files\python\lib\site-packages\stagesep2\executor.py", line 39, in run
    cls.analyse_video(each_ssv, analyser_list, result_reporter)
  File "C:\Program Files\python\lib\site-packages\stagesep2\executor.py", line 77, in analyse_video
    result = each_analyser.run(frame, ssv_video)
  File "C:\Program Files\python\lib\site-packages\stagesep2\analyser\match_template.py", line 18, in run
    fi.load_template(pic_object_list=(each_pic.pic_path, each_pic.cv_object))
TypeError: load_template() got an unexpected keyword argument 'pic_object_list'

**Comment by williamfzc** [comment]
之前修复了这个问题然后忘记release新包了。。
你重新更新下 `pip install --upgrade stagesep2`，当前最新的应该是0.2.6。
刚手动验证了下应该不会有问题了。

**Comment by 1281758787** [comment]
更新能成功运行了，谢谢。
